import type { SocialChannel } from "@/lib/enums";

export type CatalogCreator = {
  channel: SocialChannel;
  handle: string;
  displayName: string;
  locationCity: string;
  categories: string[];
  followers: number;
  engagementRate: number;
  averageViews: number;
  averageLikes: number;
};

export const DISCOVERY_CITIES = [
  "Lagos",
  "Abuja",
  "Port Harcourt",
  "Kano",
  "Ibadan",
  "Enugu",
  "Benin City",
  "Kaduna",
  "Jos",
  "Asaba",
  "Calabar",
  "Warri",
  "Abeokuta",
] as const;

export const DISCOVERY_CATALOG: CatalogCreator[] = [
  {
    channel: "INSTAGRAM",
    handle: "amaka.creates",
    displayName: "Amaka Creates",
    locationCity: "Abuja",
    categories: ["Lifestyle", "Food & Drink"],
    followers: 85_000,
    engagementRate: 4.2,
    averageViews: 18_400,
    averageLikes: 3_570,
  },
  {
    channel: "TIKTOK",
    handle: "tunde.reels",
    displayName: "Tunde Reels",
    locationCity: "Lagos",
    categories: ["Comedy", "Tech"],
    followers: 210_000,
    engagementRate: 6.1,
    averageViews: 94_000,
    averageLikes: 12_810,
  },
  {
    channel: "YOUTUBE",
    handle: "zainab.fits",
    displayName: "Zainab Fits",
    locationCity: "Kano",
    categories: ["Fashion"],
    followers: 45_000,
    engagementRate: 3.4,
    averageViews: 22_000,
    averageLikes: 1_530,
  },
  {
    channel: "INSTAGRAM",
    handle: "kelechi.eats",
    displayName: "Kelechi Eats",
    locationCity: "Lagos",
    categories: ["Food & Drink", "Lifestyle"],
    followers: 162_000,
    engagementRate: 5.1,
    averageViews: 41_000,
    averageLikes: 8_260,
  },
  {
    channel: "TIKTOK",
    handle: "lola.moves",
    displayName: "Lola Moves",
    locationCity: "Lagos",
    categories: ["Fitness & Wellness", "Lifestyle"],
    followers: 340_000,
    engagementRate: 7.4,
    averageViews: 180_000,
    averageLikes: 25_160,
  },
  {
    channel: "INSTAGRAM",
    handle: "seyi.skincare",
    displayName: "Seyi Skin",
    locationCity: "Ibadan",
    categories: ["Beauty", "Lifestyle"],
    followers: 78_000,
    engagementRate: 4.8,
    averageViews: 16_200,
    averageLikes: 3_740,
  },
  {
    channel: "YOUTUBE",
    handle: "nabil.drives",
    displayName: "Nabil Drives",
    locationCity: "Abuja",
    categories: ["Automotive", "Tech"],
    followers: 128_000,
    engagementRate: 3.1,
    averageViews: 54_000,
    averageLikes: 3_970,
  },
  {
    channel: "TIKTOK",
    handle: "funke.jokes",
    displayName: "Funke Jokes",
    locationCity: "Ibadan",
    categories: ["Comedy"],
    followers: 520_000,
    engagementRate: 8.2,
    averageViews: 310_000,
    averageLikes: 42_640,
  },
  {
    channel: "INSTAGRAM",
    handle: "halima.gold",
    displayName: "Halima Gold",
    locationCity: "Kano",
    categories: ["Fashion", "Beauty"],
    followers: 96_000,
    engagementRate: 5.6,
    averageViews: 21_000,
    averageLikes: 5_380,
  },
  {
    channel: "YOUTUBE",
    handle: "chuka.explains",
    displayName: "Chuka Explains",
    locationCity: "Enugu",
    categories: ["Education", "Finance"],
    followers: 67_000,
    engagementRate: 4.0,
    averageViews: 28_500,
    averageLikes: 2_680,
  },
  {
    channel: "TIKTOK",
    handle: "bisi.beats",
    displayName: "Bisi Beats",
    locationCity: "Lagos",
    categories: ["Music", "Lifestyle"],
    followers: 275_000,
    engagementRate: 6.8,
    averageViews: 140_000,
    averageLikes: 18_700,
  },
  {
    channel: "INSTAGRAM",
    handle: "tomiwa.home",
    displayName: "Tomiwa Home",
    locationCity: "Port Harcourt",
    categories: ["Home & DIY", "Lifestyle"],
    followers: 54_000,
    engagementRate: 3.9,
    averageViews: 11_800,
    averageLikes: 2_110,
  },
  {
    channel: "INSTAGRAM",
    handle: "adaeze.glow",
    displayName: "Adaeze Glow",
    locationCity: "Enugu",
    categories: ["Beauty", "Fashion"],
    followers: 188_000,
    engagementRate: 5.4,
    averageViews: 36_000,
    averageLikes: 10_150,
  },
  {
    channel: "TIKTOK",
    handle: "deji.codes",
    displayName: "Deji Codes",
    locationCity: "Lagos",
    categories: ["Tech", "Education"],
    followers: 91_000,
    engagementRate: 5.9,
    averageViews: 48_000,
    averageLikes: 5_370,
  },
  {
    channel: "YOUTUBE",
    handle: "yetunde.travels",
    displayName: "Yetunde Travels",
    locationCity: "Calabar",
    categories: ["Travel", "Lifestyle"],
    followers: 39_000,
    engagementRate: 3.7,
    averageViews: 19_400,
    averageLikes: 1_440,
  },
  {
    channel: "INSTAGRAM",
    handle: "ibrahim.fit",
    displayName: "Ibrahim Fit",
    locationCity: "Kaduna",
    categories: ["Fitness & Wellness", "Sports"],
    followers: 73_000,
    engagementRate: 4.5,
    averageViews: 14_600,
    averageLikes: 3_280,
  },
  {
    channel: "TIKTOK",
    handle: "lara.looks",
    displayName: "Lara Looks",
    locationCity: "Lagos",
    categories: ["Fashion", "Beauty"],
    followers: 410_000,
    engagementRate: 6.4,
    averageViews: 220_000,
    averageLikes: 26_240,
  },
  {
    channel: "INSTAGRAM",
    handle: "musa.money",
    displayName: "Musa Money",
    locationCity: "Abuja",
    categories: ["Finance", "Education"],
    followers: 112_000,
    engagementRate: 3.6,
    averageViews: 18_900,
    averageLikes: 4_030,
  },
  {
    channel: "YOUTUBE",
    handle: "gbemi.cooks",
    displayName: "Gbemi Cooks",
    locationCity: "Abeokuta",
    categories: ["Food & Drink"],
    followers: 58_000,
    engagementRate: 4.9,
    averageViews: 24_000,
    averageLikes: 2_840,
  },
  {
    channel: "TIKTOK",
    handle: "obinna.pitch",
    displayName: "Obinna Pitch",
    locationCity: "Enugu",
    categories: ["Sports", "Comedy"],
    followers: 198_000,
    engagementRate: 7.1,
    averageViews: 88_000,
    averageLikes: 14_060,
  },
  {
    channel: "INSTAGRAM",
    handle: "khadija.soft",
    displayName: "Khadija Soft",
    locationCity: "Jos",
    categories: ["Parenting", "Lifestyle"],
    followers: 64_000,
    engagementRate: 4.3,
    averageViews: 12_400,
    averageLikes: 2_750,
  },
  {
    channel: "YOUTUBE",
    handle: "wale.reviews",
    displayName: "Wale Reviews",
    locationCity: "Lagos",
    categories: ["Tech", "Gaming"],
    followers: 149_000,
    engagementRate: 3.8,
    averageViews: 61_000,
    averageLikes: 5_660,
  },
  {
    channel: "TIKTOK",
    handle: "simi.street",
    displayName: "Simi Street",
    locationCity: "Warri",
    categories: ["News & Culture", "Comedy"],
    followers: 305_000,
    engagementRate: 6.9,
    averageViews: 156_000,
    averageLikes: 21_040,
  },
  {
    channel: "INSTAGRAM",
    handle: "folake.space",
    displayName: "Folake Space",
    locationCity: "Ibadan",
    categories: ["Home & DIY", "Business"],
    followers: 41_000,
    engagementRate: 3.2,
    averageViews: 8_600,
    averageLikes: 1_310,
  },
  {
    channel: "INSTAGRAM",
    handle: "nnamdi.auto",
    displayName: "Nnamdi Auto",
    locationCity: "Asaba",
    categories: ["Automotive"],
    followers: 87_000,
    engagementRate: 3.5,
    averageViews: 15_200,
    averageLikes: 3_040,
  },
  {
    channel: "TIKTOK",
    handle: "ife.plays",
    displayName: "Ife Plays",
    locationCity: "Benin City",
    categories: ["Gaming", "Comedy"],
    followers: 236_000,
    engagementRate: 7.8,
    averageViews: 128_000,
    averageLikes: 18_410,
  },
  {
    channel: "YOUTUBE",
    handle: "bukola.learn",
    displayName: "Bukola Learn",
    locationCity: "Ibadan",
    categories: ["Education", "Parenting"],
    followers: 33_000,
    engagementRate: 4.6,
    averageViews: 14_800,
    averageLikes: 1_520,
  },
  {
    channel: "INSTAGRAM",
    handle: "aisha.runs",
    displayName: "Aisha Runs",
    locationCity: "Abuja",
    categories: ["Fitness & Wellness", "Sports"],
    followers: 119_000,
    engagementRate: 5.2,
    averageViews: 24_600,
    averageLikes: 6_190,
  },
  {
    channel: "TIKTOK",
    handle: "kunle.night",
    displayName: "Kunle Night",
    locationCity: "Lagos",
    categories: ["Music", "Lifestyle"],
    followers: 680_000,
    engagementRate: 5.8,
    averageViews: 290_000,
    averageLikes: 39_440,
  },
  {
    channel: "INSTAGRAM",
    handle: "nneka.studio",
    displayName: "Nneka Studio",
    locationCity: "Port Harcourt",
    categories: ["Fashion", "Business"],
    followers: 52_000,
    engagementRate: 4.1,
    averageViews: 10_900,
    averageLikes: 2_130,
  },
];

export function catalogKey(channel: string, handle: string) {
  return `${channel}:${handle.trim().replace(/^@/, "").toLowerCase()}`;
}

export const CATALOG_BY_KEY = new Map(
  DISCOVERY_CATALOG.map((row) => [catalogKey(row.channel, row.handle), row]),
);
