// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Generate/migrate still need a URL. Vercel `prisma generate` during
    // install often runs before env is injected; runtime uses DATABASE_URL.
    url:
      process.env["DATABASE_URL"]?.trim() ||
      "postgresql://127.0.0.1:5432/prisma_generate",
  },
});
