ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'APPLICATION_WITHDRAWN';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'OFFER_COUNTERED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'TERMS_ACCEPTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'DELIVERABLE_SUBMITTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'REVISION_REQUESTED';
